collections:
  authors:
    output: true
baseurl: /pjlabuda
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "authors"
    values:
      layout: "project"
      number: "07"
      project_title: "Test Title"
