collections:
  projects:
    output: true
    sort_by: number
baseurl: /pjlabuda
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"
      number: "99"
      title: "Test Title"
      short_desc: "No description."
