collections:
  authors:
    output: true
baseurl: /pjlabuda
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "_authors"
    values:
      layout: "project" # overrides previous default layout
